language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
script: "rake spec"
branches:
  only:
    - master
    - travis
env:
  matrix:
    - PUPPET_VERSION="~> 2.7.0"
    - PUPPET_VERSION="~> 3.0.0"
    - PUPPET_VERSION="~> 3.1.0"
    - PUPPET_VERSION="~> 3.2.0"
    - PUPPET_VERSION="~> 3.3.0"
notifications:
  email: false
gemfile: .gemfile