language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=3.1.0 FACTER_VERSION=1.7.6
  - PUPPET_VERSION=3.4.0 FACTER_VERSION=2.0.2
  - PUPPET_VERSION=3.6.0 FACTER_VERSION=2.1.0
  # This are not necessarily the versions of facter that corespond with puppet
notifications:
  email: false
gemfile: .gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION=3.1.0 FACTER_VERSION=1.7.6 #https://github.com/travis-ci/travis-ci/issues/1237